name: deployment
on:   
   
   push:
   
jobs:
    build:
     name: Build Web    
  
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       
       - name: Output Run Number
         run: echo "RUN=$(echo ${{ github.run_number }} | tr / -)" >> $GITHUB_ENV

       - name: Output Run Number
         run: mv prod.sql V${{ env.RUN }}__createuser.sql
                
       - name: Run a script
         run: docker run --rm -v "./:/flyway/sql" -v "./:/flyway/conf" dhoer/flyway:alpine migrate
